name: ASP.NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build ./PandaHR.WebAPI/PandaHR.Api.sln --configuration Release
    - name: Run test
      run: dotnet test ./PandaHR.WebAPI/tests/PandaHR.Api.UnitTests/PandaHR.Api.UnitTests.csproj --configuration Release
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
